### ISSUE TITLE
burn sub?

### ISSUE THREAD

**Issue by kaizoku75** [SKGHD/Handy#2]

**Comment by niskala5570** [comment]
Are u encoding anime? Guess Im not alone ( ͡° ͜ʖ ͡°)
At the additional flags, just put `-s "1"  --subtitle-burned "1"`
Unless u have multiple sub track, 1 is enough.
I also remuxed mkv with additional font in it to test and it worked.

**Comment by kaizoku75** [comment]
yes Im... thnks its working
 how did u remix mkv with sub and fonts?

**Comment by niskala5570** [comment]
just use mkvtoolnix (・∀・)👍

**Comment by truemate1** [comment]
> Are u encoding anime? Guess Im not alone ( ͡° ͜ʖ ͡°)
> At the additional flags, just put `-s "1" --subtitle-burned "1"`
> Unless u have multiple sub track, 1 is enough.
> I also remuxed mkv with additional font in it to test and it worked.

do you know how to change the resolution in this colab script.. as its 480p,720, and 1080p.. needed 540p

**Comment by niskala5570** [comment]
@truemate1 
At the first markdown section, put `RESOLUTION = "540p" #@param ["480p","540p", "720p", "1080p"]`
so u can easily choose it later.

At `def set_resolution():` , add 
`elif RESOLUTION=="540p":
    w, h = "960" , "540"`
(just copy paste from similar code and put any resolution u wanted)

---
and make sure u save to ur drive or it'll reset lol

**Comment by SKGHD** [comment]
@truemate1 Saw your email, added 540p :)

**Comment by truemate1** [comment]
> @truemate1
> At the first markdown section, put `RESOLUTION = "540p" #@param ["480p","540p", "720p", "1080p"]`
> so u can easily choose it later....

thanks, buddy... You and SKGHD really saved my time..as from when i was trying to do it but nope...

btw did u know how to put those brame lookahead etc options there
SKGHD given this but its not working out there.
–bframes ‘8’ --rc-lookahead ‘40’ --no-rect
shows error
[17:13:12] hb_init: starting libhb thread
[17:13:12] thread 7f5c6a429700 started (“libhb”)
unknown option (–bframes)

HandBrake has exited.

**Comment by niskala5570** [comment]
1. (っ.❛ ᴗ ❛.)っ
> –bframes ‘8’ --rc-lookahead ‘40’ --no-rect
2. Thats not the correct syntax, use this instead:
`-x bframes=8:rc-lookahead=40:no-rect`
See this: [Handbrake CLI Reference](https://handbrake.fr/docs/en/1.3.0/cli/command-line-reference.html) and [HB CLI Options](https://handbrake.fr/docs/en/1.3.0/cli/cli-options.html)

Edit: [This reddit post might as well answer your question.](https://www.reddit.com/r/handbrake/comments/fkmnxi/handbrake_advanced_options_syntax/)
Gd luck (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by truemate1** [comment]
u awesome dude

 

is there any other social acc where i can follow/ talk with you

 
 

Sent: Tuesday, April 20, 2021 at 4:17 AM

**Comment by niskala5570** [comment]
@truemate1 check out my profile then.
de wa.... I'll stop replying on this issues

**Comment by truemate1** [comment]
kazukiii... suzukiiiii my new frend okies

 
 

Sent: Tuesday, April 20, 2021 at 11:31 PM
